In [10]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [7]:
training_set=tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


In [8]:
validation_set=tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [9]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [5]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 88.    82.5   89.  ]
   [179.25 172.25 180.25]
   [176.75 169.75 177.75]
   ...
   [185.5  178.5  185.5 ]
   [171.75 164.75 171.75]
   [197.75 190.75 197.75]]

  [[ 88.5   82.5   89.5 ]
   [176.   169.   177.  ]
   [175.5  168.5  176.5 ]
   ...
   [185.75 178.75 185.75]
   [191.5  184.5  191.5 ]
   [179.5  172.5  179.5 ]]

  [[ 90.5   84.    91.5 ]
   [180.5  173.5  181.5 ]
   [172.75 165.75 173.75]
   ...
   [177.   170.   177.  ]
   [195.75 188.75 195.75]
   [189.5  182.5  189.5 ]]

  ...

  [[ 81.5   73.5   82.5 ]
   [163.   153.   164.  ]
   [159.25 149.25 160.25]
   ...
   [141.25 131.25 140.25]
   [146.5  136.5  145.5 ]
   [138.75 128.75 137.75]]

  [[ 85.75  77.    86.75]
   [167.   157.   168.  ]
   [162.75 152.75 163.75]
   ...
   [146.75 136.75 145.75]
   [130.   120.   129.  ]
   [146.25 136.25 145.25]]

  [[ 84.5   76.5   85.5 ]
   [164.75 154.75 165.75]
   [159.5  149.5  160.5 ]
   ...
   [126.   116.   125.  ]
   [139.75 129.75 138.75]
   [130.25 120.25 12

In [3]:
import tensorflow as tf

# Define the CNN model
cnn = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(38, activation='softmax')
])


ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
from tensorflow.keras.layers import Dense,Conv2D
from tensorflow.keras.layers import Sequential

In [ ]:
cnn = Sequential()

In [ ]:
cnn.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
cnn.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(tf.keras.layers.Dropout(0.25))

In [ ]:
cnn.add(tf.keras.layers.Flatten())

In [ ]:
cnn.add(tf.keras.layers.Dense(units=1500,activation='relu'))

In [ ]:
cnn.add(tf.keras.layers.Dropout(0.4)) #To avoid overfitting

In [ ]:
cnn.add(tf.keras.layers.Dense(units=38,activation='softmax'))

In [ ]:
cnn.compile(optimizer=tf.keras.optimizers.legacy.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
cnn.summary()